### signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "id": "ssh9930",
  "password": "12345",
  "name" : "송승환",
  "location": "asdlkfjsadjkl",
  "role": "USER"
}


### signin
POST http://localhost:8080/auth/signin
Content-Type: application/x-www-form-urlencoded

id=ssh9930&password=12345

### signin (특수문자 비밀번호 예시 - 반드시 URL 인코딩)
POST http://localhost:8080/auth/signin
Content-Type: application/x-www-form-urlencoded

id=ssh9930&password=P%40ss%2Bword%26%3D100%25

### /centers/
GET localhost:8080/centers

### /centers/members/
GET localhost:8080/centers/members

#
