spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: was
    maximum-sessions: 20

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    pbkdf2_pepper: ${PBKDF2_PEPPER}

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      root: debug