services:
  mysql:
    image: mysql:8.0
    container_name: senifit-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - senifit-network

  redis:
    image: redis:7-alpine
    container_name: senifit-redis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - senifit-network

  spring-boot:
    image: ${SPRING_BOOT_IMAGE}
    container_name: senifit-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./cert:/app/cert:ro
      - ${SSL_KEYSTORE_PATH}:${SSL_KEYSTORE_PATH}:ro
      - /apps/senifit/logs/was:/app/logs
    ports:
      - "8443:8443"
    networks:
      - senifit-network
  admin:
    image: ${ADMIN_BOOT_IMAGE}
    container_name: senifit-admin
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
    volumes:
      - /apps/senifit/logs/admin:/app/logs
    ports:
      - "8082:8082"
    networks:
      - senifit-network

networks:
  senifit-network:
    driver: bridge
