### get /centers/members
GET localhost:8080/centers/members

### get /centers/members/{memberid}
GET localhost:8080/centers/members/208

### post /centers/members
POST localhost:8080/centers/members
Content-Type: application/json

{
  "name": "음력테스트",
  "birthDate": "2000-03-03",
  "gender": 1,
  "memberRank": 3,
  "isSolar": false
}

### put /centers/members/{memberid}
PUT localhost:8080/centers/members/208
Content-Type: application/json

{
  "name": "음력테스트",
  "birthDate": "2000-03-03",
  "gender": 1,
  "memberRank": 3,
  "isSolar": true
}

### delete /centers/members/{memberid}
DELETE localhost:8080/centers/members/3

