### get /records
GET localhost:8080/records

### post /records
POST localhost:8080/records
Content-Type: application/json

{
  "programId": 1113,
  "participants": [204,205],
  "routineKind": "workout_programs_selections_byPopular",
  "cognitiveKind": "workout_kinds_cognitive_kinds_taekwondo",
  "singingKind": "workout_kinds_singing",
  "durationKind": "workout_duration_30minutes",
  "targetKind": "workout_kinds_calisthenic_targets_arms"
}

### put /records/{recordId}
PUT localhost:8080/records/641

### delete /records/{recordid}
DELETE localhost:8080/records/1
