### get /records
GET localhost:8080/records

### post /records
POST localhost:8080/records
Content-Type: application/json

{
  "programId": 306,
  "participants": [204,205],
  "startTime": "2025-08-10 12:22:33",
  "endTime": "2025-08-10 13:22:33",
  "routineKind": "workout_programs_selections_personal",
  "cognitiveKind": "workout_kinds_cognitive_kinds_taekwondo",
  "singingKind": "workout_kinds_singing",
  "durationKind": "workout_duration_60minutes",
  "targetKind": "workout_kinds_calisthenic_targets_abs"
}

### delete /records/{recordid}
DELETE localhost:8080/records/1
